name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run default tests
      run: lein test
    - name: Run minimal dependency tests
      run: lein with-profiles minimal test
